name: Release Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    
    - name: Check version change
      id: version_check
      run: |
        # Get current version from Info.plist
        CURRENT_VERSION=$(plutil -p Macontainer/Info.plist | grep CFBundleShortVersionString | cut -d'"' -f4)
        
        # Get previous version from last commit
        git checkout HEAD~1 -- Macontainer/Info.plist 2>/dev/null || echo "No previous version"
        PREVIOUS_VERSION=$(plutil -p Macontainer/Info.plist 2>/dev/null | grep CFBundleShortVersionString | cut -d'"' -f4 || echo "none")
        
        # Restore current Info.plist
        git checkout HEAD -- Macontainer/Info.plist
        
        echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        echo "version_changed=$([ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ] && echo "true" || echo "false")" >> $GITHUB_OUTPUT
        
        echo "Current version: $CURRENT_VERSION"
        echo "Previous version: $PREVIOUS_VERSION"
    
    - name: Build (verification only)
      run: |
        xcodebuild -scheme Macontainer \
                   -configuration Release \
                   build \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGNING_ALLOWED=NO
    
    - name: Archive and Distribute
      if: steps.version_check.outputs.version_changed == 'true'
      run: |
        echo "Version changed - creating archive for distribution..."
        
        xcodebuild -scheme Macontainer \
                   -archivePath Macontainer.xcarchive \
                   -configuration Release \
                   archive \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGNING_ALLOWED=NO
    
    - name: Skip archive message
      if: steps.version_check.outputs.version_changed == 'false'
      run: |
        echo "Version unchanged - skipping archive step."
        
    - name: Create Export Options
      run: |
        cat > ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>mac-application</string>
            <key>destination</key>
            <string>export</string>
        </dict>
        </plist>
        EOF
        
    - name: Build for Release
      run: |
        xcodebuild -project Macontainer.xcodeproj \
                   -scheme Macontainer \
                   -configuration Release \
                   -destination 'platform=macOS' \
                   -archivePath ./build/Macontainer.xcarchive \
                   archive
                   
    - name: Export Archive
      run: |
        xcodebuild -exportArchive \
                   -archivePath ./build/Macontainer.xcarchive \
                   -exportPath ./build/export \
                   -exportOptionsPlist ./ExportOptions.plist
        
    - name: Create DMG
      run: |
        mkdir -p ./build/dmg
        cp -R ./build/export/Macontainer.app ./build/dmg/
        hdiutil create -volname "Macontainer" -srcfolder ./build/dmg -ov -format UDZO ./build/Macontainer.dmg
        
    - name: Get version from Info.plist
      id: version
      run: |
        VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" ./build/export/Macontainer.app/Contents/Info.plist)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: Macontainer v${{ steps.version.outputs.version }}
        body: |
          ## What's Changed
          - Auto-generated release from main branch
          
          ## Installation
          1. Download the DMG file below
          2. Open the DMG and drag Macontainer to your Applications folder
          3. Launch Macontainer from Applications
          
        files: |
          ./build/Macontainer.dmg
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macontainer-build
        path: |
          ./build/export/Macontainer.app
          ./build/Macontainer.dmg
        retention-days: 30
